-- 현재 코드
SELECT SUB.PRODUCT_CODE, (SUB.SALES_AMOUNTS * SUB.PRICE) as SALES
FROM (SELECT P.PRODUCT_CODE, S.PRODUCT_ID, SUM(S.SALES_AMOUNT) as SALES_AMOUNTS, P.PRICE
FROM OFFLINE_SALE S
JOIN PRODUCT P
ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY S.PRODUCT_ID) SUB
ORDER BY SALES DESC, PRODUCT_CODE;

-- 이전 코드
SELECT PRODUCT_CODE, (SALES_AMOUNT*PRICE) as SALES
FROM (SELECT OFFLINE_SALE_ID, OFFLINE_SALE.PRODUCT_ID, PRODUCT_CODE, SUM(SALES_AMOUNT) as SALES_AMOUNT, PRODUCT.PRICE
FROM OFFLINE_SALE
    INNER JOIN PRODUCT
    ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT_CODE
     ) sub
ORDER BY SALES DESC, PRODUCT_CODE