-- 재구매가 일어난 상품과 회원 리스트 구하기
-- 최신 풀이
SELECT B.USER_ID, B.PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) as CNT
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID) as B
WHERE CNT >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC;


-- 이전 풀이
SELECT USER_ID, PRODUCT_ID FROM (SELECT USER_ID, PRODUCT_ID, COUNT(PRODUCT_ID) as CNT
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
) AS SUB
WHERE SUB.CNT >= 2
ORDER BY USER_ID, PRODUCT_ID DESC;