-- 현재 코드
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID=A.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY B.PUBLISHED_DATE;

-- 옛날 코드 2
SELECT BOOK_ID, AUTHOR_NAME, date_format(PUBLISHED_DATE, '20%y-%m-%d') as PUBLISHED_DATE
FROM BOOK
    INNER JOIN AUTHOR
    WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID AND BOOK.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE

-- 옛날 코드 1
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK
    INNER JOIN AUTHOR
    WHERE AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID AND BOOK.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE