SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD B
LEFT JOIN USED_GOODS_FILE F
ON B.BOARD_ID=F.BOARD_ID
WHERE B.VIEWS=(SELECT MAX(B.VIEWS) as MAX_VIEWS
FROM USED_GOODS_BOARD B
LEFT JOIN USED_GOODS_FILE F
ON B.BOARD_ID=F.BOARD_ID)
ORDER BY FILE_ID DESC