-- 조건에 맞는 개발자 찾기
SELECT DISTINCT(D.ID), D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS as D
RIGHT JOIN (SELECT CODE
            FROM SKILLCODES
            WHERE (NAME='C#') OR (NAME='Python')) as S
    ON ((LENGTH(BIN(D.SKILL_CODE)) >= LENGTH(BIN(S.CODE)))
            AND SUBSTR(RIGHT(BIN(SKILL_CODE), LENGTH(BIN(S.CODE))), 1,1) = 1)
ORDER BY D.ID ASC;