-- 특정 물고기를 잡은 총 수 구하기

SELECT COUNT(*) as FISH_COUNT
FROM (SELECT FISH.ID, FISH.FISH_TYPE, FISH.LENGTH, FISH.TIME, NAME.FISH_NAME
FROM FISH_INFO as FISH
LEFT JOIN FISH_NAME_INFO as NAME
ON NAME.FISH_TYPE = FISH.FISH_TYPE) SUB
WHERE FISH_NAME='BASS' OR FISH_NAME='SNAPPER'