-- 현재 코드
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I
ON O.ANIMAL_ID=I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID, O.NAME

-- 이전 코드
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_INS as i right join ANIMAL_OUTS as o
USING (ANIMAL_ID)
WHERE i.ANIMAL_ID IS NULL
AND o.ANIMAL_ID IS NOT NULL
ORDER BY 1