SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE (I.ANIMAL_ID IS NOT NULL AND O.ANIMAL_ID IS NOT NULL)
AND (I.SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female') AND O.SEX_UPON_OUTCOME NOT IN ('Intact Male', 'Intact Female'))
ORDER BY 1;